// docs: quant#essvi-slices-with-arbitrage-free-interpolation
//! Backs the eSSVI example on the quant catalog page.

use stochastic_rs::quant::vol_surface::SsviParams;
use stochastic_rs::quant::vol_surface::essvi::calibrate_essvi;
use stochastic_rs::quant::vol_surface::ssvi::SsviSlice;

#[test]
fn essvi_slices_recover_a_global_ssvi_surface_and_interpolate_without_arbitrage() {
  // Market slices generated by a global SSVI surface (ρ = −0.4, η = 0.6, γ = 0.4) at four maturities.
  let params = SsviParams::new(-0.4, 0.6, 0.4);
  let maturities = [0.25, 0.5, 1.0, 2.0];
  let ks: Vec<f64> = (0..21).map(|i| -0.5 + 0.05 * i as f64).collect();
  let slices: Vec<SsviSlice<f64>> = maturities
    .iter()
    .map(|&t| SsviSlice {
      log_moneyness: ks.clone(),
      total_variance: ks
        .iter()
        .map(|&k| params.total_variance(k, 0.04 * t))
        .collect(),
      theta: 0.04 * t,
    })
    .collect();

  // Anchored (ρ, ψ) per slice, going forward in maturity within the butterfly and calendar bounds.
  let surface = calibrate_essvi(&slices, &maturities);
  assert!(surface.is_butterfly_free() && surface.is_calendar_spread_free());
  for (slice, &t) in surface.slices.iter().zip(&maturities) {
    assert!((slice.rho + 0.4).abs() < 2e-3);
    assert!((slice.total_variance(0.2) - params.total_variance(0.2, 0.04 * t)).abs() < 2e-6);
  }

  // Between the slices the parameters interpolate linearly, keeping w non-decreasing in t.
  let w_early = surface.total_variance(0.1, 0.75);
  let w_late = surface.total_variance(0.1, 1.5);
  assert!(w_early > surface.total_variance(0.1, 0.5) && w_late > w_early);
}
