// docs: tutorials/svi-volatility-surface
//! Calibrates the global SSVI parameters to four maturity slices and reads the surface.

use stochastic_rs::quant::vol_surface::SsviParams;
use stochastic_rs::quant::vol_surface::SsviSurface;
use stochastic_rs::quant::vol_surface::ssvi::SsviSlice;
use stochastic_rs::quant::vol_surface::ssvi::calibrate_ssvi;

#[test]
fn ssvi_recovers_its_parameters_and_is_arbitrage_free() {
  // Slices generated by SSVI with rho = -0.4, eta = 0.6, gamma = 0.4 and theta_t = 0.04 t.
  let truth = SsviParams::new(-0.4, 0.6, 0.4);
  let maturities = vec![0.25, 0.5, 1.0, 2.0];
  let ks = (0..21).map(|i| -0.5 + 0.05 * i as f64).collect::<Vec<_>>();
  let slices = maturities
    .iter()
    .map(|&t| SsviSlice {
      log_moneyness: ks.clone(),
      total_variance: ks
        .iter()
        .map(|&k| truth.total_variance(k, 0.04 * t))
        .collect(),
      theta: 0.04 * t, // ATM total variance of the slice
    })
    .collect::<Vec<_>>();

  let fit = calibrate_ssvi(&slices, None);
  assert!((fit.rho + 0.4).abs() < 1e-6 && (fit.eta - 0.6).abs() < 1e-6);
  assert!(fit.satisfies_no_butterfly_condition()); // eta (1 + |rho|) <= 2

  let surface = SsviSurface::new(fit, slices.iter().map(|s| s.theta).collect(), maturities);
  assert!(surface.is_calendar_spread_free(&ks));
  assert!((surface.implied_vol(0.0, 0.75) - 0.2).abs() < 1e-12); // theta(t) is linear in t
  assert!(surface.local_vol(0.0, 0.75).is_finite()); // Dupire, from the analytic derivatives
}
