// docs: tutorials/heston
//! Calibrates Heston to call prices generated by known parameters and recovers them.

use stochastic_rs::quant::OptionType;
use stochastic_rs::quant::calibration::MarketSlice;
use stochastic_rs::quant::calibration::heston::HestonCalibrator;
use stochastic_rs::quant::pricing::heston::HestonPricer;
use stochastic_rs::traits::CalibrationResult;
use stochastic_rs::traits::Calibrator;
use stochastic_rs::traits::ModelPricer;

#[test]
fn heston_calibrator_recovers_generating_parameters() {
  let (s, r) = (100.0, 0.02);
  let truth = HestonPricer::new(0.05, -0.6, 1.8, 0.06, 0.5, None);
  let strikes = (0..9).map(|i| 80.0 + 5.0 * i as f64).collect::<Vec<_>>();
  let slices = [0.25, 0.5, 1.0].map(|tau| MarketSlice {
    prices: strikes
      .iter()
      .map(|&k| truth.price_call(s, k, r, 0.0, tau))
      .collect(),
    is_call: vec![true; strikes.len()],
    strikes: strikes.clone(),
    tau,
  });

  // No initial guess: the calibrator starts from its fallback parameters.
  let calibrator =
    HestonCalibrator::from_slices(None, &slices, s, r, None, OptionType::Call, false);
  let result = calibrator.calibrate(None).unwrap();
  let p = result.params();
  assert!(result.converged() && result.rmse() < 1e-3);
  assert!((p.v0 - 0.05).abs() < 1e-3 && (p.rho + 0.6).abs() < 1e-2);
  assert!((p.kappa - 1.8).abs() < 0.05 && (p.sigma - 0.5).abs() < 1e-2);
}
