//! Canonical calendar arithmetic primitives.
//!
//! Single source of truth for leap-year predicate, month-length lookup,
//! month addition (with optional end-of-month preservation), day arithmetic
//! and weekday extraction. Used by [`super::day_count`], [`super::schedule`],
//! [`super::business_day`], and [`crate::cashflows`].
//!
//! Before v2.3.0 these helpers existed in three places with subtly different
//! semantics: [`super::day_count::add_months_clamped`] (non-EOM, `pub`),
//! `schedule::add_months(eom)` (EOM-aware, `pub(crate)`), and the cashflows
//! alias `use day_count::add_months_clamped as add_months;`. This split
//! produced **EOM inconsistency**: a swap schedule generated by
//! [`super::schedule::ScheduleBuilder`] would preserve end-of-month if
//! `end_of_month(true)`, but the cashflows leg generator would not — silently.
//!
//! All three call sites now route through [`add_months`] (this module). The
//! non-EOM legacy entry [`super::day_count::add_months_clamped`] is kept as
//! a thin `#[deprecated]` wrapper so existing downstream callers keep
//! compiling; remove in v3.0.

use chrono::Datelike;
use chrono::NaiveDate;
use chrono::Weekday;

/// Gregorian leap-year predicate: `year` is divisible by 4 and not by 100,
/// or divisible by 400.
pub fn is_leap_year(year: i32) -> bool {
  (year % 4 == 0 && year % 100 != 0) || (year % 400 == 0)
}

/// Days in `month` of `year`, with `month ∈ 1..=12`. Panics on out-of-range
/// month (Rust `chrono::Datelike::month` always returns 1..=12, so this
/// branch is unreachable from valid `NaiveDate`s).
pub fn days_in_month(year: i32, month: u32) -> u32 {
  match month {
    1 | 3 | 5 | 7 | 8 | 10 | 12 => 31,
    4 | 6 | 9 | 11 => 30,
    2 => {
      if is_leap_year(year) {
        29
      } else {
        28
      }
    }
    _ => panic!("days_in_month: invalid month {month}; expected 1..=12"),
  }
}

/// Add `months` calendar months to `date`. When `eom = true`, an input that
/// falls on the last day of its month is mapped to the last day of the
/// target month (ISDA EOM rule). When `eom = false`, the day-of-month is
/// clamped to the target month's last day if the input day-of-month would
/// overflow.
///
/// # Examples
///
/// ```
/// use chrono::NaiveDate;
/// use stochastic_rs_quant::calendar::date_math::add_months;
///
/// let feb_28 = NaiveDate::from_ymd_opt(2023, 2, 28).unwrap();
/// // EOM=false: 28 → 28 (not month-end, just clamp).
/// assert_eq!(
///   add_months(feb_28, 1, false),
///   NaiveDate::from_ymd_opt(2023, 3, 28).unwrap()
/// );
/// // EOM=true: 28 is February's last day → map to March's last day (31).
/// assert_eq!(
///   add_months(feb_28, 1, true),
///   NaiveDate::from_ymd_opt(2023, 3, 31).unwrap()
/// );
///
/// // Clamp on day-of-month overflow (Jan 31 → Feb has 28 days).
/// let jan_31 = NaiveDate::from_ymd_opt(2023, 1, 31).unwrap();
/// assert_eq!(
///   add_months(jan_31, 1, false),
///   NaiveDate::from_ymd_opt(2023, 2, 28).unwrap()
/// );
/// ```
pub fn add_months(date: NaiveDate, months: i32, eom: bool) -> NaiveDate {
  let total = date.year() * 12 + date.month0() as i32 + months;
  let target_year = total.div_euclid(12);
  let target_month = (total.rem_euclid(12) + 1) as u32;
  let max_day = days_in_month(target_year, target_month);

  let day = if eom && date.day() == days_in_month(date.year(), date.month()) {
    max_day
  } else {
    date.day().min(max_day)
  };

  NaiveDate::from_ymd_opt(target_year, target_month, day)
    .expect("add_months: clamped (year, month, day) must yield a valid NaiveDate")
}

/// Shift `date` by `days` calendar days. Negative values shift backward.
/// Saturates to chrono's representable range on overflow rather than
/// panicking — production callers should not hit either extreme.
pub fn add_days(date: NaiveDate, days: i32) -> NaiveDate {
  let saturation = if days >= 0 {
    NaiveDate::MAX
  } else {
    NaiveDate::MIN
  };
  date.checked_add_signed(chrono::Duration::days(days as i64))
    .unwrap_or(saturation)
}

/// ISO weekday of `date` (`Mon..=Sun`). Thin wrapper over
/// [`chrono::Datelike::weekday`] kept here so the calendar layer does not
/// leak `chrono::Datelike` into downstream call sites.
pub fn weekday(date: NaiveDate) -> Weekday {
  date.weekday()
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn is_leap_year_gregorian_rule() {
    assert!(is_leap_year(2024));
    assert!(!is_leap_year(2023));
    assert!(!is_leap_year(1900));
    assert!(is_leap_year(2000));
  }

  #[test]
  fn days_in_month_february_branches_on_leap() {
    assert_eq!(days_in_month(2024, 2), 29);
    assert_eq!(days_in_month(2023, 2), 28);
    assert_eq!(days_in_month(2024, 1), 31);
    assert_eq!(days_in_month(2024, 4), 30);
  }

  #[test]
  #[should_panic(expected = "invalid month")]
  fn days_in_month_panics_on_invalid_month() {
    let _ = days_in_month(2024, 13);
  }

  #[test]
  fn add_months_eom_false_clamps() {
    let jan_31 = NaiveDate::from_ymd_opt(2024, 1, 31).unwrap();
    assert_eq!(
      add_months(jan_31, 1, false),
      NaiveDate::from_ymd_opt(2024, 2, 29).unwrap()
    );
    assert_eq!(
      add_months(jan_31, 13, false),
      NaiveDate::from_ymd_opt(2025, 2, 28).unwrap()
    );
  }

  #[test]
  fn add_months_eom_true_preserves_month_end() {
    let feb_29 = NaiveDate::from_ymd_opt(2024, 2, 29).unwrap();
    assert_eq!(
      add_months(feb_29, 1, true),
      NaiveDate::from_ymd_opt(2024, 3, 31).unwrap()
    );
    assert_eq!(
      add_months(feb_29, 6, true),
      NaiveDate::from_ymd_opt(2024, 8, 31).unwrap()
    );
    // Non month-end input is not EOM-promoted.
    let feb_28 = NaiveDate::from_ymd_opt(2023, 2, 28).unwrap();
    assert_eq!(
      add_months(feb_28, 1, true),
      NaiveDate::from_ymd_opt(2023, 3, 31).unwrap(),
      "Feb-28 in non-leap year is month-end and should EOM-promote"
    );
  }

  #[test]
  fn add_months_backward() {
    let mar_31 = NaiveDate::from_ymd_opt(2024, 3, 31).unwrap();
    assert_eq!(
      add_months(mar_31, -1, false),
      NaiveDate::from_ymd_opt(2024, 2, 29).unwrap()
    );
    assert_eq!(
      add_months(mar_31, -12, false),
      NaiveDate::from_ymd_opt(2023, 3, 31).unwrap()
    );
  }

  #[test]
  fn add_days_basic() {
    let d = NaiveDate::from_ymd_opt(2024, 2, 28).unwrap();
    assert_eq!(add_days(d, 1), NaiveDate::from_ymd_opt(2024, 2, 29).unwrap());
    assert_eq!(
      add_days(d, -28),
      NaiveDate::from_ymd_opt(2024, 1, 31).unwrap()
    );
  }

  #[test]
  fn weekday_known_value() {
    let mon = NaiveDate::from_ymd_opt(2024, 1, 1).unwrap();
    assert_eq!(weekday(mon), Weekday::Mon);
  }
}
