//! # Distribution fitting
//!
//! Maximum-likelihood fits of the skewed return distributions in
//! `stochastic-rs-distributions` — Johnson SU, Hansen's skewed Student-t
//! (with location and scale) and the variance gamma — each maximising
//! $\sum_i \log f(x_i \mid \theta)$ with the distribution's own closed-form
//! density in unconstrained coordinates (log scales, $\eta = 2 + e^{\vartheta}$,
//! $\lambda = \tanh\vartheta$), from the best point of a small starting grid
//! through a Nelder–Mead simplex with one restart. Standard errors are the
//! inverse observed information from a central-difference Hessian at the
//! optimum, as in [`crate::evt`].
//!
//! $$
//! \hat\theta = \arg\max_\theta \sum_{i=1}^{n}\log f(x_i \mid \theta),\qquad
//! \widehat{\mathrm{Cov}}(\hat\theta) = \bigl(-\nabla^2\ell(\hat\theta)\bigr)^{-1}.
//! $$
//!
//! # References
//! - Johnson, "Systems of Frequency Curves Generated by Methods of
//!   Translation", Biometrika, 36(1/2), 149-176 (1949).
//!   DOI: 10.1093/biomet/36.1-2.149
//! - Hansen, "Autoregressive Conditional Density Estimation", International
//!   Economic Review, 35(3), 705-730 (1994). DOI: 10.2307/2527081
//! - Madan, Carr, Chang, "The Variance Gamma Process and Option Pricing",
//!   European Finance Review, 2(1), 79-105 (1998). DOI: 10.1023/A:1009703431535

pub mod johnson_su;
pub mod skew_t;
#[cfg(test)]
mod tests;
pub mod variance_gamma;

use argmin::core::CostFunction;
use argmin::core::Executor;
use argmin::core::Gradient;
use argmin::core::State;
use argmin::solver::linesearch::MoreThuenteLineSearch;
use argmin::solver::quasinewton::LBFGS;
pub use johnson_su::JohnsonSuFit;
pub use johnson_su::johnson_su_fit;
use ndarray::ArrayView1;
pub use skew_t::SkewTFit;
pub use skew_t::skew_t_fit;
pub use variance_gamma::VarianceGammaFit;
pub use variance_gamma::variance_gamma_fit;

use crate::optim::nelder_mead_vec;
use crate::traits::FloatExt;

/// The sample as `f64`, with the size and moment checks every fitter shares.
pub(crate) fn sample<T: FloatExt>(data: ArrayView1<T>, minimum: usize) -> (Vec<f64>, f64, f64) {
  let x: Vec<f64> = data
    .iter()
    .map(|v| v.to_f64().unwrap_or(f64::NAN))
    .collect();
  let n = x.len();
  assert!(
    n >= minimum,
    "need at least {minimum} observations, got {n}"
  );
  assert!(
    x.iter().all(|v| v.is_finite()),
    "observations must be finite"
  );
  let mean = x.iter().sum::<f64>() / n as f64;
  let sd = (x.iter().map(|v| (v - mean) * (v - mean)).sum::<f64>() / (n as f64 - 1.0)).sqrt();
  assert!(sd > 0.0, "observations must not be constant");
  (x, mean, sd)
}

/// Best starting point of `starts` under `objective`, a Nelder–Mead simplex
/// with one restart, then an L-BFGS polish with central-difference
/// gradients that is kept only when it lowers the objective — the flat
/// ridges of these likelihoods stall a simplex short of the optimum.
/// Returns the optimum, the iteration count and whether the simplex met
/// its tolerance.
pub(crate) fn minimise<F: Fn(&[f64]) -> f64 + Clone>(
  starts: &[Vec<f64>],
  objective: F,
) -> (Vec<f64>, usize, bool) {
  let start = starts
    .iter()
    .min_by(|a, b| objective(a).partial_cmp(&objective(b)).unwrap())
    .expect("non-empty starting grid");
  let (theta, iters, converged) = nelder_mead_vec(start, 5_000, &objective);
  let (theta, iters_restart, converged_restart) = nelder_mead_vec(&theta, 5_000, &objective);
  let (theta, iters_polish) = Polish {
    objective: objective.clone(),
  }
  .run(theta);
  (
    theta,
    iters + iters_restart + iters_polish,
    converged || converged_restart,
  )
}

/// The objective as an `argmin` problem with numerical gradients.
#[derive(Clone)]
struct Polish<F> {
  objective: F,
}

impl<F: Fn(&[f64]) -> f64 + Clone> Polish<F> {
  fn run(&self, theta: Vec<f64>) -> (Vec<f64>, usize) {
    let start_cost = (self.objective)(&theta);
    let linesearch = MoreThuenteLineSearch::new();
    let solver = LBFGS::new(linesearch, 10);
    let result = Executor::new(self.clone(), solver)
      .configure(|state| state.param(theta.clone()).max_iters(200))
      .run();
    match result {
      Ok(res) => {
        let iters = res.state.get_iter() as usize;
        match res.state.get_best_param() {
          Some(best) if (self.objective)(best) < start_cost => (best.clone(), iters),
          _ => (theta, iters),
        }
      }
      Err(_) => (theta, 0),
    }
  }
}

impl<F: Fn(&[f64]) -> f64 + Clone> CostFunction for Polish<F> {
  type Param = Vec<f64>;
  type Output = f64;

  fn cost(&self, theta: &Self::Param) -> Result<Self::Output, argmin::core::Error> {
    Ok((self.objective)(theta))
  }
}

impl<F: Fn(&[f64]) -> f64 + Clone> Gradient for Polish<F> {
  type Param = Vec<f64>;
  type Gradient = Vec<f64>;

  fn gradient(&self, theta: &Self::Param) -> Result<Self::Gradient, argmin::core::Error> {
    let mut grad = vec![0.0; theta.len()];
    for i in 0..theta.len() {
      let step = 1e-6 * (1.0 + theta[i].abs());
      let mut plus = theta.clone();
      let mut minus = theta.clone();
      plus[i] += step;
      minus[i] -= step;
      grad[i] = ((self.objective)(&plus) - (self.objective)(&minus)) / (2.0 * step);
    }
    Ok(grad)
  }
}

/// Negative log-likelihood from a per-observation log-density, `1e300`
/// when any term is not finite.
pub(crate) fn negative_log_likelihood<F: Fn(f64) -> f64>(x: &[f64], log_density: F) -> f64 {
  let mut total = 0.0;
  for &v in x {
    let l = log_density(v);
    if !l.is_finite() {
      return 1e300;
    }
    total -= l;
  }
  total
}
