//! # stochastic-rs-py
//!
//! PyO3 cdylib that registers all `PyXxx` wrappers generated by the
//! `py_distribution!` / `py_process_*!` macros across the
//! `stochastic-rs-distributions` and `stochastic-rs-stochastic` sub-crates.
//!
//! Build with maturin (see `pyproject.toml` at the workspace root) — the
//! resulting wheel exposes the Python module `stochastic_rs`.

#![allow(non_snake_case)]

use pyo3::prelude::*;

#[pymodule]
#[pyo3(name = "stochastic_rs")]
fn stochastic_rs_python(m: &Bound<'_, PyModule>) -> PyResult<()> {
  // Distributions
  use stochastic_rs_distributions::alpha_stable::PyAlphaStable;
  use stochastic_rs_distributions::beta::PyBeta;
  use stochastic_rs_distributions::binomial::PyBinomial;
  use stochastic_rs_distributions::cauchy::PyCauchy;
  use stochastic_rs_distributions::chi_square::PyChiSquared;
  use stochastic_rs_distributions::exp::PyExp;
  use stochastic_rs_distributions::gamma::PyGamma;
  use stochastic_rs_distributions::geometric::PyGeometric;
  use stochastic_rs_distributions::hypergeometric::PyHypergeometric;
  use stochastic_rs_distributions::inverse_gauss::PyInverseGauss;
  use stochastic_rs_distributions::lognormal::PyLogNormal;
  use stochastic_rs_distributions::normal::PyNormal;
  use stochastic_rs_distributions::normal_inverse_gauss::PyNormalInverseGauss;
  use stochastic_rs_distributions::pareto::PyPareto;
  use stochastic_rs_distributions::poisson::PyPoissonD;
  use stochastic_rs_distributions::studentt::PyStudentT;
  use stochastic_rs_distributions::uniform::PyUniform;
  use stochastic_rs_distributions::weibull::PyWeibull;
  // Stochastic — autoregressive
  use stochastic_rs_stochastic::autoregressive::agrach::PyAgarch;
  use stochastic_rs_stochastic::autoregressive::ar::PyARp;
  use stochastic_rs_stochastic::autoregressive::arch::PyArch;
  use stochastic_rs_stochastic::autoregressive::arima::PyArima;
  use stochastic_rs_stochastic::autoregressive::egarch::PyEgarch;
  use stochastic_rs_stochastic::autoregressive::garch::PyGarch;
  use stochastic_rs_stochastic::autoregressive::ma::PyMAq;
  use stochastic_rs_stochastic::autoregressive::sarima::PySarima;
  use stochastic_rs_stochastic::autoregressive::tgarch::PyTgarch;
  // Stochastic — diffusion
  use stochastic_rs_stochastic::diffusion::cev::PyCev;
  use stochastic_rs_stochastic::diffusion::cfou::PyCfou;
  use stochastic_rs_stochastic::diffusion::cir::PyCir;
  use stochastic_rs_stochastic::diffusion::fcir::PyFcir;
  use stochastic_rs_stochastic::diffusion::feller::PyFellerLogistic;
  use stochastic_rs_stochastic::diffusion::fgbm::PyFgbm;
  use stochastic_rs_stochastic::diffusion::fjacobi::PyFJacobi;
  use stochastic_rs_stochastic::diffusion::fou::PyFou;
  use stochastic_rs_stochastic::diffusion::fouque::PyFouqueOU2D;
  use stochastic_rs_stochastic::diffusion::gbm::PyGbm;
  use stochastic_rs_stochastic::diffusion::gbm_ih::PyGbmIh;
  use stochastic_rs_stochastic::diffusion::gbm_log::PyGbmLog;
  use stochastic_rs_stochastic::diffusion::gompertz::PyGompertz;
  use stochastic_rs_stochastic::diffusion::jacobi::PyJacobi;
  use stochastic_rs_stochastic::diffusion::kimura::PyKimura;
  use stochastic_rs_stochastic::diffusion::ou::PyOu;
  use stochastic_rs_stochastic::diffusion::quadratic::PyQuadratic;
  use stochastic_rs_stochastic::diffusion::verhulst::PyVerhulst;
  // Stochastic — interest rates
  use stochastic_rs_stochastic::interest::adg::PyAdg;
  use stochastic_rs_stochastic::interest::bgm::PyBgm;
  use stochastic_rs_stochastic::interest::duffie_kan::PyDuffieKan;
  use stochastic_rs_stochastic::interest::duffie_kan_jump_exp::PyDuffieKanJumpExp;
  use stochastic_rs_stochastic::interest::fractional_vasicek::PyFVasicek;
  use stochastic_rs_stochastic::interest::hjm::PyHjm;
  use stochastic_rs_stochastic::interest::ho_lee::PyHoLee;
  use stochastic_rs_stochastic::interest::hull_white::PyHullWhite;
  use stochastic_rs_stochastic::interest::hull_white_2f::PyHullWhite2F;
  use stochastic_rs_stochastic::interest::vasicek::PyVasicek;
  use stochastic_rs_stochastic::interest::wu_zhang::PyWuZhangD;
  // Stochastic — jump
  use stochastic_rs_stochastic::jump::bates::PyBates;
  use stochastic_rs_stochastic::jump::bilateral_gamma::PyBilateralGamma;
  use stochastic_rs_stochastic::jump::bilateral_gamma::PyBilateralGammaMotion;
  use stochastic_rs_stochastic::jump::cgmy::PyCgmy;
  use stochastic_rs_stochastic::jump::cts::PyCts;
  use stochastic_rs_stochastic::jump::ig::PyIg;
  use stochastic_rs_stochastic::jump::jump_fou::PyJumpFou;
  use stochastic_rs_stochastic::jump::jump_fou_custom::PyJumpFOUCustom;
  use stochastic_rs_stochastic::jump::kobol::PyKoBoL;
  use stochastic_rs_stochastic::jump::kou::PyKou;
  use stochastic_rs_stochastic::jump::levy_diffusion::PyLevyDiffusion;
  use stochastic_rs_stochastic::jump::merton::PyMerton;
  use stochastic_rs_stochastic::jump::mjd_log::PyMjdLog;
  use stochastic_rs_stochastic::jump::nig::PyNig;
  use stochastic_rs_stochastic::jump::rdts::PyRdts;
  use stochastic_rs_stochastic::jump::vg::PyVg;
  // Stochastic — noise
  use stochastic_rs_stochastic::noise::cfgns::PyCfgns;
  use stochastic_rs_stochastic::noise::cgns::PyCgns;
  use stochastic_rs_stochastic::noise::fgn::PyFgn;
  use stochastic_rs_stochastic::noise::gn::PyGn;
  use stochastic_rs_stochastic::noise::wn::PyWn;
  // Stochastic — process
  use stochastic_rs_stochastic::process::bm::PyBm;
  use stochastic_rs_stochastic::process::cbms::PyCbms;
  use stochastic_rs_stochastic::process::ccustom::PyCompoundCustom;
  use stochastic_rs_stochastic::process::cfbms::PyCfbms;
  use stochastic_rs_stochastic::process::cpoisson::PyCompoundPoisson;
  use stochastic_rs_stochastic::process::customjt::PyCustomJt;
  use stochastic_rs_stochastic::process::fbm::PyFbm;
  use stochastic_rs_stochastic::process::hawkes::PyHawkes;
  use stochastic_rs_stochastic::process::lfsm::PyLfsm;
  use stochastic_rs_stochastic::process::poisson::PyPoisson;
  use stochastic_rs_stochastic::process::subordinator::alpha_stable::PyAlphaStableSubordinator;
  use stochastic_rs_stochastic::process::subordinator::ctrw::PyCtrw;
  use stochastic_rs_stochastic::process::subordinator::gamma_subordinator::PyGammaSubordinator;
  use stochastic_rs_stochastic::process::subordinator::ig_subordinator::PyIGSubordinator;
  use stochastic_rs_stochastic::process::subordinator::inverse_alpha_stable::PyInverseAlphaStableSubordinator;
  use stochastic_rs_stochastic::process::subordinator::poisson_subordinator::PyPoissonSubordinator;
  use stochastic_rs_stochastic::process::subordinator::tempered_stable::PyTemperedStableSubordinator;
  use stochastic_rs_stochastic::process::volterra::PyVolterra;
  // Stochastic — sheet
  use stochastic_rs_stochastic::sheet::fbs::PyFbs;
  // Stochastic — volatility
  use stochastic_rs_stochastic::volatility::bates_svj::PyBatesSvj;
  use stochastic_rs_stochastic::volatility::bergomi::PyBergomi;
  use stochastic_rs_stochastic::volatility::fheston::PyRoughHeston;
  use stochastic_rs_stochastic::volatility::heston::PyHeston;
  use stochastic_rs_stochastic::volatility::heston_log::PyHestonLog;
  use stochastic_rs_stochastic::volatility::rbergomi::PyRoughBergomi;
  use stochastic_rs_stochastic::volatility::sabr::PySabr;
  use stochastic_rs_stochastic::volatility::svcgmy::PySvcgmy;

  m.add_class::<PyFbm>()?;
  m.add_class::<PyLfsm>()?;
  m.add_class::<PyBm>()?;
  m.add_class::<PyCbms>()?;
  m.add_class::<PyCfbms>()?;
  m.add_class::<PyPoisson>()?;
  m.add_class::<PyHawkes>()?;
  m.add_class::<PyCustomJt>()?;
  m.add_class::<PyCompoundPoisson>()?;
  m.add_class::<PyCompoundCustom>()?;
  m.add_class::<PyVolterra>()?;
  m.add_class::<PyAlphaStableSubordinator>()?;
  m.add_class::<PyInverseAlphaStableSubordinator>()?;
  m.add_class::<PyPoissonSubordinator>()?;
  m.add_class::<PyGammaSubordinator>()?;
  m.add_class::<PyIGSubordinator>()?;
  m.add_class::<PyTemperedStableSubordinator>()?;
  m.add_class::<PyCtrw>()?;
  m.add_class::<PyFgn>()?;
  m.add_class::<PyGn>()?;
  m.add_class::<PyWn>()?;
  m.add_class::<PyCgns>()?;
  m.add_class::<PyCfgns>()?;
  m.add_class::<PyCev>()?;
  m.add_class::<PyCfou>()?;
  m.add_class::<PyCir>()?;
  m.add_class::<PyFcir>()?;
  m.add_class::<PyFellerLogistic>()?;
  m.add_class::<PyFgbm>()?;
  m.add_class::<PyFJacobi>()?;
  m.add_class::<PyFou>()?;
  m.add_class::<PyFouqueOU2D>()?;
  m.add_class::<PyGbm>()?;
  m.add_class::<PyGbmIh>()?;
  m.add_class::<PyGbmLog>()?;
  m.add_class::<PyGompertz>()?;
  m.add_class::<PyJacobi>()?;
  m.add_class::<PyKimura>()?;
  m.add_class::<PyOu>()?;
  m.add_class::<PyQuadratic>()?;
  m.add_class::<PyVerhulst>()?;
  m.add_class::<PyCgmy>()?;
  m.add_class::<PyCts>()?;
  m.add_class::<PyIg>()?;
  m.add_class::<PyNig>()?;
  m.add_class::<PyRdts>()?;
  m.add_class::<PyVg>()?;
  m.add_class::<PyMerton>()?;
  m.add_class::<PyMjdLog>()?;
  m.add_class::<PyKoBoL>()?;
  m.add_class::<PyKou>()?;
  m.add_class::<PyLevyDiffusion>()?;
  m.add_class::<PyBates>()?;
  m.add_class::<PyBilateralGamma>()?;
  m.add_class::<PyBilateralGammaMotion>()?;
  m.add_class::<PyJumpFou>()?;
  m.add_class::<PyJumpFOUCustom>()?;
  m.add_class::<PyBatesSvj>()?;
  m.add_class::<PyBergomi>()?;
  m.add_class::<PyHeston>()?;
  m.add_class::<PyHestonLog>()?;
  m.add_class::<PyRoughBergomi>()?;
  m.add_class::<PySabr>()?;
  m.add_class::<PyRoughHeston>()?;
  m.add_class::<PySvcgmy>()?;
  m.add_class::<PyDuffieKan>()?;
  m.add_class::<PyDuffieKanJumpExp>()?;
  m.add_class::<PyFVasicek>()?;
  m.add_class::<PyVasicek>()?;
  m.add_class::<PyBgm>()?;
  m.add_class::<PyWuZhangD>()?;
  m.add_class::<PyAdg>()?;
  m.add_class::<PyHjm>()?;
  m.add_class::<PyHoLee>()?;
  m.add_class::<PyHullWhite>()?;
  m.add_class::<PyHullWhite2F>()?;
  m.add_class::<PyAgarch>()?;
  m.add_class::<PyARp>()?;
  m.add_class::<PyArch>()?;
  m.add_class::<PyArima>()?;
  m.add_class::<PyEgarch>()?;
  m.add_class::<PyGarch>()?;
  m.add_class::<PyMAq>()?;
  m.add_class::<PySarima>()?;
  m.add_class::<PyTgarch>()?;
  m.add_class::<PyFbs>()?;
  m.add_class::<PyBeta>()?;
  m.add_class::<PyAlphaStable>()?;
  m.add_class::<PyCauchy>()?;
  m.add_class::<PyChiSquared>()?;
  m.add_class::<PyExp>()?;
  m.add_class::<PyGamma>()?;
  m.add_class::<PyInverseGauss>()?;
  m.add_class::<PyLogNormal>()?;
  m.add_class::<PyNormal>()?;
  m.add_class::<PyNormalInverseGauss>()?;
  m.add_class::<PyPareto>()?;
  m.add_class::<PyStudentT>()?;
  m.add_class::<PyUniform>()?;
  m.add_class::<PyWeibull>()?;
  m.add_class::<PyBinomial>()?;
  m.add_class::<PyGeometric>()?;
  m.add_class::<PyHypergeometric>()?;
  m.add_class::<PyPoissonD>()?;

  use stochastic_rs_quant::python::PyAsianPricer;
  use stochastic_rs_quant::python::PyAssetOrNothingPricer;
  use stochastic_rs_quant::python::PyBSMCalibrator;
  use stochastic_rs_quant::python::PyBSMFourier;
  use stochastic_rs_quant::python::PyBSMPricer;
  use stochastic_rs_quant::python::PyBarrierPricer;
  use stochastic_rs_quant::python::PyBatesFourier;
  use stochastic_rs_quant::python::PyBjerksundStensland2002Pricer;
  use stochastic_rs_quant::python::PyCGMYFourier;
  use stochastic_rs_quant::python::PyCIRBond;
  use stochastic_rs_quant::python::PyCarrMadanPricer;
  use stochastic_rs_quant::python::PyCashOrNothingPricer;
  use stochastic_rs_quant::python::PyCliquetPricer;
  use stochastic_rs_quant::python::PyCompoundPricer;
  use stochastic_rs_quant::python::PyDoubleBarrierPricer;
  use stochastic_rs_quant::python::PyDoubleHestonCalibrator;
  use stochastic_rs_quant::python::PyDoubleHestonFourier;
  use stochastic_rs_quant::python::PyDrawdownStats;
  use stochastic_rs_quant::python::PyExpectedShortfall;
  use stochastic_rs_quant::python::PyFixedLookbackPricer;
  use stochastic_rs_quant::python::PyFloatingLookbackPricer;
  use stochastic_rs_quant::python::PyGapPricer;
  use stochastic_rs_quant::python::PyHKDECalibrator;
  use stochastic_rs_quant::python::PyHKDEFourier;
  use stochastic_rs_quant::python::PyHestonCalibrator;
  use stochastic_rs_quant::python::PyHscmCalibrator;
  use stochastic_rs_quant::python::PyHscmMarketOption;
  use stochastic_rs_quant::python::PyHscmModel;
  use stochastic_rs_quant::python::PyHullWhiteBond;
  use stochastic_rs_quant::python::PyHestonFourier;
  use stochastic_rs_quant::python::PyHestonPricer;
  use stochastic_rs_quant::python::PyImpliedVolSurface;
  use stochastic_rs_quant::python::PyKirkSpreadPricer;
  use stochastic_rs_quant::python::PyKouFourier;
  use stochastic_rs_quant::python::PyLevyCalibrator;
  use stochastic_rs_quant::python::PyMCBarrierPricer;
  use stochastic_rs_quant::python::PyMarketSlice;
  use stochastic_rs_quant::python::PyMerton1976Pricer;
  use stochastic_rs_quant::python::PyMertonJDFourier;
  use stochastic_rs_quant::python::PyNigFourier;
  use stochastic_rs_quant::python::PyRBergomiCalibrator;
  use stochastic_rs_quant::python::PySVJCalibrator;
  use stochastic_rs_quant::python::PySabrCalibrator;
  use stochastic_rs_quant::python::PySabrPricer;
  use stochastic_rs_quant::python::PySimpleChooserPricer;
  use stochastic_rs_quant::python::PySsviCalibrator;
  use stochastic_rs_quant::python::PySsviParams;
  use stochastic_rs_quant::python::PySuperSharePricer;
  use stochastic_rs_quant::python::PySviCalibrator;
  use stochastic_rs_quant::python::PySviRawParams;
  use stochastic_rs_quant::python::PyVaR;
  use stochastic_rs_quant::python::PyVarianceGammaFourier;
  use stochastic_rs_quant::python::PyVarianceSwapPricer;
  use stochastic_rs_quant::python::PyVasicekBond;

  m.add_class::<PyBSMPricer>()?;
  m.add_class::<PyHestonPricer>()?;
  m.add_class::<PySabrPricer>()?;
  m.add_class::<PyMerton1976Pricer>()?;
  m.add_class::<PyAsianPricer>()?;
  m.add_class::<PyBarrierPricer>()?;
  m.add_class::<PyCashOrNothingPricer>()?;
  m.add_class::<PyAssetOrNothingPricer>()?;
  m.add_class::<PyFloatingLookbackPricer>()?;
  m.add_class::<PyBjerksundStensland2002Pricer>()?;
  m.add_class::<PyVarianceSwapPricer>()?;
  m.add_class::<PyBSMFourier>()?;
  m.add_class::<PyHestonFourier>()?;
  m.add_class::<PyDoubleHestonFourier>()?;
  m.add_class::<PyHKDEFourier>()?;
  m.add_class::<PyVarianceGammaFourier>()?;
  m.add_class::<PyCGMYFourier>()?;
  m.add_class::<PyMertonJDFourier>()?;
  m.add_class::<PyKouFourier>()?;
  m.add_class::<PyNigFourier>()?;
  m.add_class::<PyBatesFourier>()?;
  m.add_class::<PyCarrMadanPricer>()?;
  m.add_class::<PyVasicekBond>()?;
  m.add_class::<PyCIRBond>()?;
  m.add_class::<PyHullWhiteBond>()?;
  m.add_class::<PyMarketSlice>()?;
  m.add_class::<PyBSMCalibrator>()?;
  m.add_class::<PyHestonCalibrator>()?;
  m.add_class::<PySabrCalibrator>()?;
  m.add_class::<PySVJCalibrator>()?;
  m.add_class::<PyDoubleHestonCalibrator>()?;
  m.add_class::<PyLevyCalibrator>()?;
  m.add_class::<PySviRawParams>()?;
  m.add_class::<PySsviParams>()?;
  m.add_class::<PyCompoundPricer>()?;
  m.add_class::<PySimpleChooserPricer>()?;
  m.add_class::<PyCliquetPricer>()?;
  m.add_class::<PyGapPricer>()?;
  m.add_class::<PySuperSharePricer>()?;
  m.add_class::<PyFixedLookbackPricer>()?;
  m.add_class::<PyDoubleBarrierPricer>()?;
  m.add_class::<PyMCBarrierPricer>()?;
  m.add_class::<PyKirkSpreadPricer>()?;
  m.add_class::<PyImpliedVolSurface>()?;
  m.add_class::<PySviCalibrator>()?;
  m.add_class::<PySsviCalibrator>()?;
  m.add_class::<PyHKDECalibrator>()?;
  m.add_class::<PyHscmModel>()?;
  m.add_class::<PyHscmMarketOption>()?;
  m.add_class::<PyHscmCalibrator>()?;
  m.add_class::<PyRBergomiCalibrator>()?;
  m.add_class::<PyVaR>()?;
  m.add_class::<PyExpectedShortfall>()?;
  m.add_class::<PyDrawdownStats>()?;

  use stochastic_rs_quant::python::PyAlmgrenChrissPlan;
  use stochastic_rs_quant::python::PyCgmysvCalibrator;
  use stochastic_rs_quant::python::PyDiscountCurve;
  use stochastic_rs_quant::python::PyKyleEquilibrium;
  use stochastic_rs_quant::python::PyNelsonSiegel;
  use stochastic_rs_quant::python::PyOrderBook;
  use stochastic_rs_quant::python::PySabrCapletCalibrator;
  use stochastic_rs_quant::python::PyZeroCouponInflationCurve;
  m.add_class::<PyAlmgrenChrissPlan>()?;
  m.add_class::<PyKyleEquilibrium>()?;
  m.add_class::<PyOrderBook>()?;
  m.add_class::<PyDiscountCurve>()?;
  m.add_class::<PyNelsonSiegel>()?;
  m.add_class::<PyZeroCouponInflationCurve>()?;
  m.add_class::<PySabrCapletCalibrator>()?;
  m.add_class::<PyCgmysvCalibrator>()?;
  m.add_function(pyo3::wrap_pyfunction!(
    stochastic_rs_quant::python::multi_period_kyle,
    m
  )?)?;
  m.add_function(pyo3::wrap_pyfunction!(
    stochastic_rs_quant::python::roll_spread,
    m
  )?)?;
  m.add_function(pyo3::wrap_pyfunction!(
    stochastic_rs_quant::python::effective_spread,
    m
  )?)?;
  m.add_function(pyo3::wrap_pyfunction!(
    stochastic_rs_quant::python::corwin_schultz_spread,
    m
  )?)?;
  m.add_function(pyo3::wrap_pyfunction!(
    stochastic_rs_quant::python::propagator_price_impact,
    m
  )?)?;
  m.add_function(pyo3::wrap_pyfunction!(
    stochastic_rs_quant::python::ledoit_wolf_shrinkage,
    m
  )?)?;
  m.add_function(pyo3::wrap_pyfunction!(
    stochastic_rs_quant::python::sample_covariance,
    m
  )?)?;
  m.add_function(pyo3::wrap_pyfunction!(
    stochastic_rs_quant::python::empirical_cvar,
    m
  )?)?;
  #[cfg(feature = "openblas")]
  {
    use stochastic_rs_quant::python::PyFamaMacBeth;
    use stochastic_rs_quant::python::PyPCA;
    use stochastic_rs_quant::python::PyPairsStrategy;
    m.add_class::<PyPCA>()?;
    m.add_class::<PyFamaMacBeth>()?;
    m.add_class::<PyPairsStrategy>()?;
  }

  use stochastic_rs_copulas::python::PyClayton;
  use stochastic_rs_copulas::python::PyEmpiricalCopula2D;
  use stochastic_rs_copulas::python::PyFrank;
  use stochastic_rs_copulas::python::PyGumbel;
  use stochastic_rs_copulas::python::PyIndependence;

  m.add_class::<PyClayton>()?;
  m.add_class::<PyGumbel>()?;
  m.add_class::<PyFrank>()?;
  m.add_class::<PyIndependence>()?;
  m.add_class::<PyEmpiricalCopula2D>()?;
  m.add_function(pyo3::wrap_pyfunction!(
    stochastic_rs_copulas::python::kendall_tau_matrix,
    m
  )?)?;
  m.add_function(pyo3::wrap_pyfunction!(
    stochastic_rs_copulas::python::tau_matrix_to_corr_matrix,
    m
  )?)?;
  m.add_function(pyo3::wrap_pyfunction!(
    stochastic_rs_copulas::python::tau_to_corr,
    m
  )?)?;
  m.add_function(pyo3::wrap_pyfunction!(
    stochastic_rs_copulas::python::corr_to_tau,
    m
  )?)?;

  use stochastic_rs_stats::python::PyAndersonDarling;
  use stochastic_rs_stats::python::PyBNSJumpTest;
  use stochastic_rs_stats::python::PyBipowerVariation;
  use stochastic_rs_stats::python::PyFouEstimate;
  use stochastic_rs_stats::python::PyFukasawaHurst;
  use stochastic_rs_stats::python::PyGaussianKDE;
  use stochastic_rs_stats::python::PyHestonMLE;
  use stochastic_rs_stats::python::PyHestonNMLECEKF;
  use stochastic_rs_stats::python::PyJarqueBera;
  use stochastic_rs_stats::python::PyLeverage;
  use stochastic_rs_stats::python::PyRealizedKernel;
  use stochastic_rs_stats::python::PyRealizedMoments;
  use stochastic_rs_stats::python::PyShapiroFrancia;
  use stochastic_rs_stats::python::PyTailIndex;
  use stochastic_rs_stats::python::PyTwoScaleRV;

  m.add_class::<PyJarqueBera>()?;
  m.add_class::<PyAndersonDarling>()?;
  m.add_class::<PyShapiroFrancia>()?;
  m.add_class::<PyFukasawaHurst>()?;
  m.add_class::<PyFouEstimate>()?;
  m.add_class::<PyHestonMLE>()?;
  m.add_class::<PyHestonNMLECEKF>()?;
  m.add_class::<PyRealizedMoments>()?;
  m.add_class::<PyBipowerVariation>()?;
  m.add_class::<PyBNSJumpTest>()?;
  m.add_class::<PyRealizedKernel>()?;
  m.add_class::<PyTwoScaleRV>()?;
  m.add_class::<PyGaussianKDE>()?;
  m.add_class::<PyTailIndex>()?;
  m.add_class::<PyLeverage>()?;

  use stochastic_rs_stats::python::PyCusum;
  use stochastic_rs_stats::python::PyPelt;
  use stochastic_rs_stats::python::PyPeriodogramFFT;
  use stochastic_rs_stats::python::PyPreAveragedVariance;
  m.add_class::<PyCusum>()?;
  m.add_class::<PyPelt>()?;
  m.add_class::<PyPeriodogramFFT>()?;
  m.add_class::<PyPreAveragedVariance>()?;
  m.add_function(pyo3::wrap_pyfunction!(
    stochastic_rs_stats::python::random_walk_metropolis,
    m
  )?)?;
  #[cfg(feature = "openblas")]
  {
    use stochastic_rs_stats::python::PyADFTest;
    use stochastic_rs_stats::python::PyERSTest;
    use stochastic_rs_stats::python::PyEngleGranger;
    use stochastic_rs_stats::python::PyGaussianHmm;
    use stochastic_rs_stats::python::PyGranger;
    use stochastic_rs_stats::python::PyHarRv;
    use stochastic_rs_stats::python::PyJohansen;
    use stochastic_rs_stats::python::PyKPSSTest;
    use stochastic_rs_stats::python::PyLeybourneMcCabeTest;
    use stochastic_rs_stats::python::PyPhillipsPerronTest;
    m.add_class::<PyADFTest>()?;
    m.add_class::<PyKPSSTest>()?;
    m.add_class::<PyPhillipsPerronTest>()?;
    m.add_class::<PyERSTest>()?;
    m.add_class::<PyLeybourneMcCabeTest>()?;
    m.add_class::<PyHarRv>()?;
    m.add_class::<PyEngleGranger>()?;
    m.add_class::<PyJohansen>()?;
    m.add_class::<PyGranger>()?;
    m.add_class::<PyGaussianHmm>()?;
  }

  Ok(())
}
