//! # stochastic-rs-py
//!
//! PyO3 cdylib that registers all `PyXxx` wrappers generated by the
//! `py_distribution!` / `py_process_*!` macros across the
//! `stochastic-rs-distributions` and `stochastic-rs-stochastic` sub-crates.
//!
//! Build with maturin (see `pyproject.toml` at the workspace root) — the
//! resulting wheel exposes the Python module `stochastic_rs`.

#![allow(non_snake_case)]

use pyo3::prelude::*;

#[pymodule]
#[pyo3(name = "stochastic_rs")]
fn stochastic_rs_python(m: &Bound<'_, PyModule>) -> PyResult<()> {
  // Distributions
  use stochastic_rs_distributions::alpha_stable::PyAlphaStable;
  use stochastic_rs_distributions::beta::PyBeta;
  use stochastic_rs_distributions::binomial::PyBinomial;
  use stochastic_rs_distributions::cauchy::PyCauchy;
  use stochastic_rs_distributions::chi_square::PyChiSquared;
  use stochastic_rs_distributions::exp::PyExp;
  use stochastic_rs_distributions::gamma::PyGamma;
  use stochastic_rs_distributions::geometric::PyGeometric;
  use stochastic_rs_distributions::hypergeometric::PyHypergeometric;
  use stochastic_rs_distributions::inverse_gauss::PyInverseGauss;
  use stochastic_rs_distributions::lognormal::PyLogNormal;
  use stochastic_rs_distributions::normal::PyNormal;
  use stochastic_rs_distributions::normal_inverse_gauss::PyNormalInverseGauss;
  use stochastic_rs_distributions::pareto::PyPareto;
  use stochastic_rs_distributions::poisson::PyPoissonD;
  use stochastic_rs_distributions::studentt::PyStudentT;
  use stochastic_rs_distributions::uniform::PyUniform;
  use stochastic_rs_distributions::weibull::PyWeibull;

  // Stochastic — autoregressive
  use stochastic_rs_stochastic::autoregressive::agrach::PyAGARCH;
  use stochastic_rs_stochastic::autoregressive::ar::PyARp;
  use stochastic_rs_stochastic::autoregressive::arch::PyARCH;
  use stochastic_rs_stochastic::autoregressive::arima::PyARIMA;
  use stochastic_rs_stochastic::autoregressive::egarch::PyEGARCH;
  use stochastic_rs_stochastic::autoregressive::garch::PyGARCH;
  use stochastic_rs_stochastic::autoregressive::ma::PyMAq;
  use stochastic_rs_stochastic::autoregressive::sarima::PySARIMA;
  use stochastic_rs_stochastic::autoregressive::tgarch::PyTGARCH;

  // Stochastic — diffusion
  use stochastic_rs_stochastic::diffusion::cev::PyCEV;
  use stochastic_rs_stochastic::diffusion::cfou::PyCFOU;
  use stochastic_rs_stochastic::diffusion::cir::PyCIR;
  use stochastic_rs_stochastic::diffusion::fcir::PyFCIR;
  use stochastic_rs_stochastic::diffusion::feller::PyFellerLogistic;
  use stochastic_rs_stochastic::diffusion::fgbm::PyFGBM;
  use stochastic_rs_stochastic::diffusion::fjacobi::PyFJacobi;
  use stochastic_rs_stochastic::diffusion::fou::PyFOU;
  use stochastic_rs_stochastic::diffusion::fouque::PyFouqueOU2D;
  use stochastic_rs_stochastic::diffusion::gbm::PyGBM;
  use stochastic_rs_stochastic::diffusion::gbm_ih::PyGBMIH;
  use stochastic_rs_stochastic::diffusion::gbm_log::PyGBMLog;
  use stochastic_rs_stochastic::diffusion::gompertz::PyGompertz;
  use stochastic_rs_stochastic::diffusion::jacobi::PyJacobi;
  use stochastic_rs_stochastic::diffusion::kimura::PyKimura;
  use stochastic_rs_stochastic::diffusion::ou::PyOU;
  use stochastic_rs_stochastic::diffusion::quadratic::PyQuadratic;
  use stochastic_rs_stochastic::diffusion::verhulst::PyVerhulst;

  // Stochastic — interest rates
  use stochastic_rs_stochastic::interest::adg::PyADG;
  use stochastic_rs_stochastic::interest::bgm::PyBGM;
  use stochastic_rs_stochastic::interest::duffie_kan::PyDuffieKan;
  use stochastic_rs_stochastic::interest::duffie_kan_jump_exp::PyDuffieKanJumpExp;
  use stochastic_rs_stochastic::interest::fractional_vasicek::PyFVasicek;
  use stochastic_rs_stochastic::interest::hjm::PyHJM;
  use stochastic_rs_stochastic::interest::ho_lee::PyHoLee;
  use stochastic_rs_stochastic::interest::hull_white::PyHullWhite;
  use stochastic_rs_stochastic::interest::hull_white_2f::PyHullWhite2F;
  use stochastic_rs_stochastic::interest::vasicek::PyVasicek;
  use stochastic_rs_stochastic::interest::wu_zhang::PyWuZhangD;

  // Stochastic — jump
  use stochastic_rs_stochastic::jump::bates::PyBates;
  use stochastic_rs_stochastic::jump::bilateral_gamma::PyBilateralGamma;
  use stochastic_rs_stochastic::jump::bilateral_gamma::PyBilateralGammaMotion;
  use stochastic_rs_stochastic::jump::cgmy::PyCGMY;
  use stochastic_rs_stochastic::jump::cts::PyCTS;
  use stochastic_rs_stochastic::jump::ig::PyIG;
  use stochastic_rs_stochastic::jump::jump_fou::PyJumpFOU;
  use stochastic_rs_stochastic::jump::jump_fou_custom::PyJumpFOUCustom;
  use stochastic_rs_stochastic::jump::kobol::PyKoBoL;
  use stochastic_rs_stochastic::jump::kou::PyKOU;
  use stochastic_rs_stochastic::jump::levy_diffusion::PyLevyDiffusion;
  use stochastic_rs_stochastic::jump::merton::PyMerton;
  use stochastic_rs_stochastic::jump::mjd_log::PyMJDLog;
  use stochastic_rs_stochastic::jump::nig::PyNIG;
  use stochastic_rs_stochastic::jump::rdts::PyRDTS;
  use stochastic_rs_stochastic::jump::vg::PyVG;

  // Stochastic — noise
  use stochastic_rs_stochastic::noise::cfgns::PyCFGNS;
  use stochastic_rs_stochastic::noise::cgns::PyCGNS;
  use stochastic_rs_stochastic::noise::fgn::PyFGN;
  use stochastic_rs_stochastic::noise::gn::PyGn;
  use stochastic_rs_stochastic::noise::wn::PyWn;

  // Stochastic — process
  use stochastic_rs_stochastic::process::bm::PyBM;
  use stochastic_rs_stochastic::process::cbms::PyCBMS;
  use stochastic_rs_stochastic::process::ccustom::PyCompoundCustom;
  use stochastic_rs_stochastic::process::cfbms::PyCFBMS;
  use stochastic_rs_stochastic::process::cpoisson::PyCompoundPoisson;
  use stochastic_rs_stochastic::process::customjt::PyCustomJt;
  use stochastic_rs_stochastic::process::fbm::PyFBM;
  use stochastic_rs_stochastic::process::hawkes::PyHawkes;
  use stochastic_rs_stochastic::process::lfsm::PyLFSM;
  use stochastic_rs_stochastic::process::poisson::PyPoisson;
  use stochastic_rs_stochastic::process::subordinator::alpha_stable::PyAlphaStableSubordinator;
  use stochastic_rs_stochastic::process::subordinator::ctrw::PyCTRW;
  use stochastic_rs_stochastic::process::subordinator::gamma_subordinator::PyGammaSubordinator;
  use stochastic_rs_stochastic::process::subordinator::ig_subordinator::PyIGSubordinator;
  use stochastic_rs_stochastic::process::subordinator::inverse_alpha_stable::PyInverseAlphaStableSubordinator;
  use stochastic_rs_stochastic::process::subordinator::poisson_subordinator::PyPoissonSubordinator;
  use stochastic_rs_stochastic::process::subordinator::tempered_stable::PyTemperedStableSubordinator;

  // Stochastic — sheet
  use stochastic_rs_stochastic::sheet::fbs::PyFBS;

  // Stochastic — volatility
  use stochastic_rs_stochastic::volatility::bates_svj::PyBatesSVJ;
  use stochastic_rs_stochastic::volatility::bergomi::PyBergomi;
  use stochastic_rs_stochastic::volatility::fheston::PyRoughHeston;
  use stochastic_rs_stochastic::volatility::heston::PyHeston;
  use stochastic_rs_stochastic::volatility::heston_log::PyHestonLog;
  use stochastic_rs_stochastic::volatility::rbergomi::PyRoughBergomi;
  use stochastic_rs_stochastic::volatility::sabr::PySABR;
  use stochastic_rs_stochastic::volatility::svcgmy::PySVCGMY;

  m.add_class::<PyFBM>()?;
  m.add_class::<PyLFSM>()?;
  m.add_class::<PyBM>()?;
  m.add_class::<PyCBMS>()?;
  m.add_class::<PyCFBMS>()?;
  m.add_class::<PyPoisson>()?;
  m.add_class::<PyHawkes>()?;
  m.add_class::<PyCustomJt>()?;
  m.add_class::<PyCompoundPoisson>()?;
  m.add_class::<PyCompoundCustom>()?;
  m.add_class::<PyAlphaStableSubordinator>()?;
  m.add_class::<PyInverseAlphaStableSubordinator>()?;
  m.add_class::<PyPoissonSubordinator>()?;
  m.add_class::<PyGammaSubordinator>()?;
  m.add_class::<PyIGSubordinator>()?;
  m.add_class::<PyTemperedStableSubordinator>()?;
  m.add_class::<PyCTRW>()?;
  m.add_class::<PyFGN>()?;
  m.add_class::<PyGn>()?;
  m.add_class::<PyWn>()?;
  m.add_class::<PyCGNS>()?;
  m.add_class::<PyCFGNS>()?;
  m.add_class::<PyCEV>()?;
  m.add_class::<PyCFOU>()?;
  m.add_class::<PyCIR>()?;
  m.add_class::<PyFCIR>()?;
  m.add_class::<PyFellerLogistic>()?;
  m.add_class::<PyFGBM>()?;
  m.add_class::<PyFJacobi>()?;
  m.add_class::<PyFOU>()?;
  m.add_class::<PyFouqueOU2D>()?;
  m.add_class::<PyGBM>()?;
  m.add_class::<PyGBMIH>()?;
  m.add_class::<PyGBMLog>()?;
  m.add_class::<PyGompertz>()?;
  m.add_class::<PyJacobi>()?;
  m.add_class::<PyKimura>()?;
  m.add_class::<PyOU>()?;
  m.add_class::<PyQuadratic>()?;
  m.add_class::<PyVerhulst>()?;
  m.add_class::<PyCGMY>()?;
  m.add_class::<PyCTS>()?;
  m.add_class::<PyIG>()?;
  m.add_class::<PyNIG>()?;
  m.add_class::<PyRDTS>()?;
  m.add_class::<PyVG>()?;
  m.add_class::<PyMerton>()?;
  m.add_class::<PyMJDLog>()?;
  m.add_class::<PyKoBoL>()?;
  m.add_class::<PyKOU>()?;
  m.add_class::<PyLevyDiffusion>()?;
  m.add_class::<PyBates>()?;
  m.add_class::<PyBilateralGamma>()?;
  m.add_class::<PyBilateralGammaMotion>()?;
  m.add_class::<PyJumpFOU>()?;
  m.add_class::<PyJumpFOUCustom>()?;
  m.add_class::<PyBatesSVJ>()?;
  m.add_class::<PyBergomi>()?;
  m.add_class::<PyHeston>()?;
  m.add_class::<PyHestonLog>()?;
  m.add_class::<PyRoughBergomi>()?;
  m.add_class::<PySABR>()?;
  m.add_class::<PyRoughHeston>()?;
  m.add_class::<PySVCGMY>()?;
  m.add_class::<PyDuffieKan>()?;
  m.add_class::<PyDuffieKanJumpExp>()?;
  m.add_class::<PyFVasicek>()?;
  m.add_class::<PyVasicek>()?;
  m.add_class::<PyBGM>()?;
  m.add_class::<PyWuZhangD>()?;
  m.add_class::<PyADG>()?;
  m.add_class::<PyHJM>()?;
  m.add_class::<PyHoLee>()?;
  m.add_class::<PyHullWhite>()?;
  m.add_class::<PyHullWhite2F>()?;
  m.add_class::<PyAGARCH>()?;
  m.add_class::<PyARp>()?;
  m.add_class::<PyARCH>()?;
  m.add_class::<PyARIMA>()?;
  m.add_class::<PyEGARCH>()?;
  m.add_class::<PyGARCH>()?;
  m.add_class::<PyMAq>()?;
  m.add_class::<PySARIMA>()?;
  m.add_class::<PyTGARCH>()?;
  m.add_class::<PyFBS>()?;
  m.add_class::<PyBeta>()?;
  m.add_class::<PyAlphaStable>()?;
  m.add_class::<PyCauchy>()?;
  m.add_class::<PyChiSquared>()?;
  m.add_class::<PyExp>()?;
  m.add_class::<PyGamma>()?;
  m.add_class::<PyInverseGauss>()?;
  m.add_class::<PyLogNormal>()?;
  m.add_class::<PyNormal>()?;
  m.add_class::<PyNormalInverseGauss>()?;
  m.add_class::<PyPareto>()?;
  m.add_class::<PyStudentT>()?;
  m.add_class::<PyUniform>()?;
  m.add_class::<PyWeibull>()?;
  m.add_class::<PyBinomial>()?;
  m.add_class::<PyGeometric>()?;
  m.add_class::<PyHypergeometric>()?;
  m.add_class::<PyPoissonD>()?;
  Ok(())
}
