[package]
name = "stochastic-rs-stats"
version.workspace = true
edition = "2024"
license = "MIT"
readme = "README.md"
description = "Statistical estimators for stochastic processes."
homepage = "https://stochastic.rust-dd.com"
documentation = "https://docs.rs/stochastic-rs-stats"
repository = "https://github.com/rust-dd/stochastic-rs"
keywords = ["statistics", "estimation", "hurst", "mle", "stochastic"]
categories = ["mathematics", "science"]

[features]
default = []
python = [
    "dep:pyo3",
    "dep:numpy",
    "stochastic-rs-core/python",
    "stochastic-rs-distributions/python",
    "stochastic-rs-stochastic/python",
]

[dependencies]
faer = { workspace = true }
faer-ext = { workspace = true, features = ["ndarray"] }
stochastic-rs-core = { workspace = true }
stochastic-rs-distributions = { workspace = true }
stochastic-rs-stochastic = { workspace = true }
ndarray = { workspace = true, features = ["rayon", "matrixmultiply-threading"] }
nalgebra = { workspace = true }
num-traits = { workspace = true }
num-complex = { workspace = true }
rand = { workspace = true }
rand_distr = { workspace = true }
roots = { workspace = true }
kendalls = { workspace = true }
levenberg-marquardt = { workspace = true }
linreg = { workspace = true }
argmin = { workspace = true }
argmin-math = { workspace = true, features = ["ndarray_latest-nolinalg", "vec"] }
gauss-quad = { workspace = true }
quadrature = { workspace = true }
sci-rs = { workspace = true }
scilib = { workspace = true }
slsqp = { workspace = true }
chrono = { workspace = true }
parking_lot = { workspace = true }
ndrustfft = { workspace = true }
anyhow = { workspace = true }
pyo3 = { workspace = true, features = ["extension-module"], optional = true }
numpy = { workspace = true, optional = true }

