//! Conditional Malliavin weights for the multi-asset log-Euler scheme.
//!
//! Reference: Kohatsu-Higa & Yasuda (2008), RIMS Kôkyûroku 1580,
//! Theorem 6.1 and equation (6.2).

use ndarray::Array1;
use ndarray::Array2;

use super::MultiHestonParams;
use super::MultiHestonPaths;
use crate::traits::FloatExt;

impl<T: FloatExt> MultiHestonParams<T> {
  /// Validate that conditional Malliavin integration by parts is exact.
  ///
  /// The implemented weights condition on the variance paths and integrate by
  /// parts over the price Brownian motions. This requires every stochastic
  /// variance shock to be independent of every price shock. A non-zero Heston
  /// leverage correlation is harmless only when `xi == 0`, because the
  /// variance path is then deterministic.
  pub fn validate_conditional_malliavin_weights(&self) -> anyhow::Result<()> {
    for (asset, params) in self.assets.iter().enumerate() {
      if !num_traits::Float::is_finite(params.xi) || !num_traits::Float::is_finite(params.rho) {
        anyhow::bail!("asset {asset} has non-finite xi or rho");
      }
      if params.xi != T::zero() && params.rho != T::zero() {
        anyhow::bail!(
          "asset {asset} has xi={:?} and rho={:?}; exact conditional Malliavin weights require xi == 0 or rho == 0",
          params.xi,
          params.rho
        );
      }
    }
    Ok(())
  }
}

impl<T: FloatExt> MultiHestonPaths<T> {
  /// Malliavin covariance matrix `gamma_F` of the conditional log-Euler model.
  pub fn malliavin_cov(&self, cross_corr: &Array2<T>, tau: T) -> Array2<T> {
    assert!(
      self.supports_conditional_malliavin_weights(),
      "conditional Malliavin covariance is not exact for stochastic leverage paths"
    );
    let d = self.n_assets;
    let n = self.n_steps;
    let dt = tau / T::from_usize_(n - 1);
    let terminal = self.terminal_prices_array();

    let mut gamma = Array2::<T>::zeros((d, d));
    for i in 0..d {
      for j in 0..d {
        let integrated_covariance = (0..n - 1)
          .map(|step| {
            (self.vols[[i, step]].max(T::zero()) * self.vols[[j, step]].max(T::zero())).sqrt() * dt
          })
          .fold(T::zero(), |sum, value| sum + value);
        gamma[[i, j]] = terminal[i] * terminal[j] * cross_corr[[i, j]] * integrated_covariance;
      }
    }
    gamma
  }

  /// Reconstruct `I_j = integral sqrt(V_j) dW_j^S` from log returns.
  ///
  /// This identity is exact for paths generated by [`MultiHestonParams::sample`]
  /// and its seeded variants, whose price update is exponential log-Euler.
  pub fn ito_integral(&self, asset: usize, r: T, tau: T) -> T {
    assert!(asset < self.n_assets, "asset index out of bounds");
    assert!(self.n_steps >= 2, "n_steps must be at least 2");
    let dt = tau / T::from_usize_(self.n_steps - 1);
    (0..self.n_steps - 1)
      .map(|step| {
        let previous = self.prices[[asset, step]];
        let next = self.prices[[asset, step + 1]];
        assert!(
          previous > T::zero() && next > T::zero(),
          "log-return reconstruction requires strictly positive prices"
        );
        let variance = self.vols[[asset, step]].max(T::zero());
        (next / previous).ln() - (r - T::from_f64_fast(0.5) * variance) * dt
      })
      .fold(T::zero(), |sum, value| sum + value)
  }

  /// Exact conditional Skorohod weights for Delta with respect to `spots[p]`.
  ///
  /// Writing `A_ij = R_ij integral sqrt(V_i V_j) dt`, `I_j = integral
  /// sqrt(V_j) dW_j^S`, and `p = param_asset`, the returned components are
  ///
  /// `H_i = S_Tp / (S_0p S_Ti) * ((A^-1 I)_i + 1 - delta_ip)`.
  ///
  /// The final `1 - delta_ip` is the divergence product-rule term omitted by
  /// treating the anticipating coefficient as an ordinary Itô integrand.
  pub fn try_malliavin_weights(
    &self,
    gamma_inv: &Array2<T>,
    param_asset: usize,
    r: T,
    tau: T,
    spots: &Array1<T>,
  ) -> anyhow::Result<Array1<T>> {
    let d = self.n_assets;
    if !self.supports_conditional_malliavin_weights() {
      anyhow::bail!(
        "paths do not satisfy the price-noise independence assumption for exact conditional Malliavin weights"
      );
    }
    if self.n_steps < 2 {
      anyhow::bail!("n_steps must be at least 2");
    }
    if self.prices.dim() != (d, self.n_steps) || self.vols.dim() != (d, self.n_steps) {
      anyhow::bail!("price and variance array shapes must match n_assets and n_steps");
    }
    if !num_traits::Float::is_finite(r) {
      anyhow::bail!("r must be finite");
    }
    if !num_traits::Float::is_finite(tau) || tau <= T::zero() {
      anyhow::bail!("tau must be finite and positive");
    }
    if gamma_inv.shape() != [d, d] {
      anyhow::bail!(
        "gamma_inv shape {:?} does not match n_assets={d}",
        gamma_inv.shape()
      );
    }
    if spots.len() != d {
      anyhow::bail!("spots length {} does not match n_assets={d}", spots.len());
    }
    if param_asset >= d {
      anyhow::bail!("param_asset={param_asset} is out of bounds for n_assets={d}");
    }
    if !num_traits::Float::is_finite(spots[param_asset]) || spots[param_asset] <= T::zero() {
      anyhow::bail!("initial spot for asset {param_asset} must be finite and positive");
    }
    if self
      .prices
      .iter()
      .any(|price| !num_traits::Float::is_finite(*price) || *price <= T::zero())
    {
      anyhow::bail!("all prices must be finite and strictly positive");
    }
    if self
      .vols
      .iter()
      .any(|variance| !num_traits::Float::is_finite(*variance) || *variance < T::zero())
    {
      anyhow::bail!("all variances must be finite and non-negative");
    }

    let terminal = self.terminal_prices_array();
    let ito = Array1::from_shape_fn(d, |asset| self.ito_integral(asset, r, tau));
    let tangent = terminal[param_asset] / spots[param_asset];

    Ok(Array1::from_shape_fn(d, |i| {
      let ordinary_integral = (0..d)
        .map(|j| gamma_inv[[i, j]] * terminal[j] * ito[j])
        .fold(T::zero(), |sum, value| sum + value);
      let correction = if i == param_asset {
        T::zero()
      } else {
        tangent / terminal[i]
      };
      tangent * ordinary_integral + correction
    }))
  }

  /// Compatibility wrapper for [`Self::try_malliavin_weights`].
  ///
  /// It panics on invalid dimensions or non-positive prices. New code should
  /// use the fallible method and keep the weights as an [`Array1`].
  pub fn malliavin_weights(
    &self,
    gamma_inv: &Array2<T>,
    param_asset: usize,
    r: T,
    tau: T,
    spots: &[T],
  ) -> Vec<T> {
    self
      .try_malliavin_weights(
        gamma_inv,
        param_asset,
        r,
        tau,
        &Array1::from_iter(spots.iter().copied()),
      )
      .expect("invalid conditional Malliavin weight inputs; use try_malliavin_weights")
      .to_vec()
  }

  /// Inverse of the Malliavin covariance matrix. Requires LAPACK.
  pub fn gamma_inv(&self, cross_corr: &Array2<T>, tau: T) -> Array2<T>
  where
    T: ndarray_linalg::Lapack,
  {
    self
      .try_gamma_inv(cross_corr, tau)
      .expect("Malliavin covariance matrix is singular; use try_gamma_inv")
  }

  /// Fallible inverse of the Malliavin covariance matrix.
  pub fn try_gamma_inv(&self, cross_corr: &Array2<T>, tau: T) -> anyhow::Result<Array2<T>>
  where
    T: ndarray_linalg::Lapack,
  {
    use ndarray_linalg::Inverse;

    if !self.supports_conditional_malliavin_weights() {
      anyhow::bail!("conditional Malliavin covariance is not exact for stochastic leverage paths");
    }
    if self.n_assets == 0 || self.n_steps < 2 {
      anyhow::bail!("paths require at least one asset and two time points");
    }
    if self.prices.dim() != (self.n_assets, self.n_steps)
      || self.vols.dim() != (self.n_assets, self.n_steps)
    {
      anyhow::bail!("price and variance array shapes must match n_assets and n_steps");
    }
    if cross_corr.shape() != [self.n_assets, self.n_assets] {
      anyhow::bail!(
        "cross_corr shape {:?} does not match n_assets={}",
        cross_corr.shape(),
        self.n_assets
      );
    }
    if !num_traits::Float::is_finite(tau) || tau <= T::zero() {
      anyhow::bail!("tau must be finite and positive");
    }
    self
      .malliavin_cov(cross_corr, tau)
      .inv()
      .map_err(|error| anyhow::anyhow!("Malliavin covariance matrix is singular: {error}"))
  }
}

#[cfg(test)]
mod tests;
