//! Every process carries the sampling backend as a type parameter: each
//! `ProcessExt` implementation is bound on a backend capability
//! (`HostBackend`, `EulerBackend` or `FgnBackend`) and every backend-typed
//! process exposes `on::<B2>()`. A process added without the parameter fails
//! here rather than shipping a second, `Cpu`-only API shape.

use std::fs;
use std::path::Path;

fn sources(dir: &Path, out: &mut Vec<(String, String)>) {
  for entry in fs::read_dir(dir).expect("src dir") {
    let path = entry.expect("entry").path();
    if path.is_dir() {
      sources(&path, out);
    } else if path.extension().is_some_and(|e| e == "rs") {
      out.push((
        path.display().to_string(),
        fs::read_to_string(&path).expect("read"),
      ));
    }
  }
}

/// The `impl<…> ProcessExt<T> for Name<…>` headers of `src`, as
/// `(generics, name, type arguments)`.
fn impl_headers(src: &str) -> Vec<(String, String, String)> {
  let mut out = Vec::new();
  let mut from = 0;
  while let Some(rel) = src[from..].find("ProcessExt<T>") {
    let at = from + rel;
    from = at + "ProcessExt<T>".len();
    // `impl<` … `>` immediately before, possibly across a line break.
    let Some(impl_start) = src[..at].rfind("impl<") else {
      continue;
    };
    let between = src[impl_start..at].trim_end();
    if !between.ends_with('>') || between.contains('{') {
      continue; // an `impl` of something else in between
    }
    let generics = between["impl<".len()..between.len() - 1].to_string();
    let rest = &src[from..];
    let Some(for_rel) = rest.find("for ") else {
      continue;
    };
    if rest[..for_rel].trim() != "" {
      continue; // `ProcessExt<T>` used as a bound, not an impl header
    }
    let after_for = &rest[for_rel + 4..];
    let Some(lt) = after_for.find('<') else {
      continue;
    };
    let name = after_for[..lt].trim().to_string();
    // type arguments end at the matching `>` (depth-aware)
    let mut depth = 0;
    let mut end = None;
    for (i, c) in after_for[lt..].char_indices() {
      match c {
        '<' => depth += 1,
        '>' => {
          depth -= 1;
          if depth == 0 {
            end = Some(lt + i);
            break;
          }
        }
        _ => {}
      }
    }
    let Some(end) = end else { continue };
    out.push((generics, name, after_for[lt + 1..end].trim().to_string()));
  }
  out
}

#[test]
fn every_process_ext_impl_is_backend_typed() {
  let mut files = Vec::new();
  sources(
    Path::new(concat!(env!("CARGO_MANIFEST_DIR"), "/src")),
    &mut files,
  );
  let mut impls = 0;
  let mut untyped = Vec::new();
  let mut missing_switch = Vec::new();
  for (path, src) in &files {
    if path.contains("/traits/") || path.ends_with("/device.rs") {
      continue;
    }
    for (generics, name, args) in impl_headers(src) {
      impls += 1;
      let bound_ok = ["B: HostBackend", "B: EulerBackend", "B: FgnBackend"]
        .iter()
        .any(|b| generics.contains(b));
      if !(bound_ok && args.ends_with(", B")) {
        untyped.push(format!(
          "{}: {name}<{args}>",
          path.rsplit("/src/").next().unwrap_or(path)
        ));
      }
    }
    // Every backend-typed struct in the file has a switch: a hand-written
    // `pub fn on<B2: …>` or one generated by the `backend_switch!` macro.
    let typed = src
      .lines()
      .filter(|l| l.trim_start().starts_with("pub struct") && l.contains("B = Cpu>"))
      .count();
    let switches = src.matches("pub fn on<B2:").count() + src.matches("backend_switch!(").count();
    if switches < typed {
      missing_switch.push(format!(
        "{}: {typed} backend-typed structs, {switches} switches",
        path.rsplit("/src/").next().unwrap_or(path)
      ));
    }
  }
  assert!(
    untyped.is_empty(),
    "ProcessExt implementations without a backend parameter:\n{}",
    untyped.join("\n")
  );
  assert!(
    impls >= 131,
    "expected the 131 process implementations, found {impls}"
  );
  assert!(
    missing_switch.is_empty(),
    "backend-typed structs without an `on::<B2>()` switch:
{}",
    missing_switch.join(
      "
"
    )
  );
}
