//! # Traits — umbrella re-export hub.

pub use stochastic_rs_copulas::traits::BivariateExt;
#[cfg(feature = "openblas")]
pub use stochastic_rs_copulas::traits::MultivariateExt;
#[cfg(feature = "python")]
pub use stochastic_rs_distributions::traits::CallableDist;
pub use stochastic_rs_distributions::traits::DistributionExt;
pub use stochastic_rs_distributions::traits::DistributionSampler;
pub use stochastic_rs_distributions::traits::FloatExt;
pub use stochastic_rs_distributions::traits::Fn1D;
pub use stochastic_rs_distributions::traits::Fn2D;
pub use stochastic_rs_distributions::traits::SimdFloatExt;
pub use stochastic_rs_quant::traits::CalibrationResult;
pub use stochastic_rs_quant::traits::Calibrator;
pub use stochastic_rs_quant::traits::Greeks;
pub use stochastic_rs_quant::traits::GreeksExt;
pub use stochastic_rs_quant::traits::Instrument;
pub use stochastic_rs_quant::traits::InstrumentExt;
pub use stochastic_rs_quant::traits::ModelPricer;
pub use stochastic_rs_quant::traits::PricerExt;
pub use stochastic_rs_quant::traits::PricingEngine;
pub use stochastic_rs_quant::traits::PricingResult;
pub use stochastic_rs_quant::traits::StandardResult;
pub use stochastic_rs_quant::traits::TimeExt;
pub use stochastic_rs_quant::traits::ToModel;
pub use stochastic_rs_stochastic::traits::ComplexPathOutput;
pub use stochastic_rs_stochastic::traits::CurveOutput;
pub use stochastic_rs_stochastic::traits::Malliavin2DExt;
pub use stochastic_rs_stochastic::traits::MalliavinExt;
pub use stochastic_rs_stochastic::traits::MultiDimensional;
pub use stochastic_rs_stochastic::traits::OneDimensional;
pub use stochastic_rs_stochastic::traits::ProcessExt;
pub use stochastic_rs_stochastic::traits::TwoDimensional;
pub use stochastic_rs_stochastic::traits::VariableDimensional;
